name: Build it!
on: [push, pull_request]
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - uses: actions/setup-python@v2
              with:
                python-version: '3.7'
                cache: 'pip' # caching pip dependencies
            - name: Installing dependencies
              run: pip install -r requirements.txt
            - name: Updating README.md
              run: python script.py

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: README.md
                  commit-msg: Update README.md
                  github-token: ${{ secrets.GITHUB_TOKEN }}
